spring.datasource.url=jdbc:postgresql://localhost:5432/retrogame_archive
spring.datasource.username=tiago
spring.datasource.password=101199

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect