spring.datasource.url=jdbc:postgresql://localhost:5432/retrogame_archive
spring.datasource.username=tiago
spring.datasource.password=101199

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=retrogame-archive-secret-key-muito-segura-2024
jwt.expiration=86400000